<a href="https://colab.research.google.com/github/Dipesh0987/Concepts-and-Technologies-of-AI/blob/main/Dipesh_Kishor_Chhetri_Week1_worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Problem - 1: Array Creation:**

Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [1]:
import numpy as np
#1)
empty_array = np.empty((2, 2))
print("1. Empty 2x2 array:")
print(empty_array)
print()
#2)
ones_array = np.ones((4, 2))
print("2. All ones 4x2 array:")
print(ones_array)
print()
#3)
filled_array = np.full((3, 3), 5)
print("3. Array filled with value 5:")
print(filled_array)
print()
#4)
sample_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(sample_array)
print("4. Zeros array with same shape as sample:")
print("Sample array:")
print(sample_array)
print("Zeros like array:")
print(zeros_like_array)
print()
#5)
ones_like_array = np.ones_like(sample_array)
print("5. Ones array with same shape as sample:")
print("Ones like array:")
print(ones_like_array)
print()
#6)
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("6. Converted list to numpy array:")
print("Original list:", new_list)
print("Numpy array:", numpy_array)

1. Empty 2x2 array:
[[1.72295543e-315 0.00000000e+000]
 [3.31971956e-316 1.65862750e-315]]

2. All ones 4x2 array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with value 5:
[[5 5 5]
 [5 5 5]
 [5 5 5]]

4. Zeros array with same shape as sample:
Sample array:
[[1 2]
 [3 4]]
Zeros like array:
[[0 0]
 [0 0]]

5. Ones array with same shape as sample:
Ones like array:
[[1 1]
 [1 1]]

6. Converted list to numpy array:
Original list: [1, 2, 3, 4]
Numpy array: [1 2 3 4]


**Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.